#this is a code linting
name: Auto Linter

on:
  push:
    paths:
      - "*.py"

  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v4

      - name: Install Linter
        run: pip install ruff

      - name: Run Linter
        run: ruff check .
