#This code is a from here linting
#heloo this is a simple file
name : Auto Linter


on: 
  push:
    paths: "*.py"


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7

      - name: Install Linter
        run: pip install ruff
      
      
